### ISSUE TITLE
Missing random distribution

### ISSUE THREAD

**Issue by serge-sans-paille** [serge-sans-paille/pythran#1270]
https://docs.scipy.org/doc/numpy/reference/routines.random.html#distributions lists random distribution supported by numpy. Several of them are not implemented in Pythonic (yet)!

**Comment by serge-sans-paille** [comment]
@paugier this one is reserved for your student!

**Comment by paugier** [comment]
Thank you @serge-sans-paille 

CC @PierreBlancfat

**Comment by paugier** [comment]
@PierreBlancfat should start to work on this (after the 19th of August and only during 2 weeks... so don't way for too much @serge-sans-paille).

By the way, @PierreBlancfat, you should follow this issue.

Numpy is a moving target... The link is broken because there were a lot of changes in `numpy.random`...

> Since Numpy version 1.17.0 the Generator can be initialized with a number of different BitGenerators. It exposes many different probability distributions. See NEP 19 for context on the updated random Numpy number routines. The legacy RandomState random number routines are still available, but limited to a single BitGenerator.

https://docs.scipy.org/doc/numpy/reference/random

See also the legacy random generation:

https://docs.scipy.org/doc/numpy/reference/random/legacy.html#distributions

**Comment by serge-sans-paille** [comment]
Closed through 398642f3ee007a0f03af914695a5d4db58646d39
