### ISSUE TITLE
Default parameter export syntax

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1374]
I work on an example with `def _dilate(image, selem, out=None, shift_x=0, shift_y=0):` (you may recognize this code).

Default parameters with something else than None are not supported yet by Transonic-Pythran, so I have to work on this feature. However, I wonder if I have to work on Transonic or directly on Pythran.

I'm not convince by the syntax
```
#export func()
#export func(int)
#export func(int, int)
def func(a=1, b=1):
    return a + b
```
It seems to me that the information that `a` and `b` can be omitted is written too many times. It's already in the Python code and it has to be added in the export commands.

Moreover, it seems incompatible with the correct (and very common) Python call `func(b=2)`. I think this is not yet supported for Pythran, but in the middle term, it should be supported.

Moreover, I don't this that this syntax (adding more export commands for default parameters) is documented in https://pythran.readthedocs.io/en/latest/MANUAL.html#concerning-pythran-specifications

For Transonic, one should just have to write (we know enough):

```
@boost
def func(a: int = 1, b: int = 1):
    ...
```

My point is that if Pythran needs more signatures, it could generate them automatically by looking at the default parameters in the Python code. If Pythran does that, I don't need to do anything in Transonic so I could directly work to implement this in Pythran.

What do you think ?

**Comment by serge-sans-paille** [comment]
I'm 100% sure transonic can achieve the goal you state. On the pythran side though, I see a few shortcomings:

1. be explicit. There's a cost behind each extra export line. This cost already hit us in the past, and still hurts us. Current syntax makes it possible to explicitly enable/disable some overloads

2. list/set handling. In the case of ``def foo(x=[])`` pythran would initialize x as an empty list, which could be a problem. This problem still exist with current code base, but at least it's possible to workaround it with explicit export.

So in the end, and most notably because of (1.), I see a place for Transonic as a pythran preprocessor, and handling defaults the way you propose is 100% in the scope of Transonic.

**Comment by serge-sans-paille** [comment]
Still not closing the issue because of the documentation issue you're pointing at.

**Comment by paugier** [comment]
Yes, it really make sense. So I'll work on this in Transonic.

> In the case of `def foo(x=[])`

Just a small remark... Anyway, even just in Python, I don't think anyone should do that because it's so confusing. So many Python developers would think that the empty list is initialized at call time whereas it is only initialize once at def time. "No mutable object as default parameter" is a good rule in Python.  `def foo(x=None): if x is None: x=[]`.
