### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [serge-sans-paille/pythran#2123]
Is it possible next time on release new version make the github release to have entry on https://github.com/john-kurkowski/tldextract/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by serge-sans-paille** [comment]
Hey o/ I'm diligently setting a  new tag for each new version, plus pushing the release on pypi. Why isn't that enough to track release?

**Comment by kloczek** [comment]
Because this RFE is only about **spreading** info about new release.
You don't need to add gh release to each tag.

**Comment by serge-sans-paille** [comment]
Understood. I think I'm in the situation described in https://github.com/dear-github/dear-github/issues/399 ... not sold on the idea of pushing release on Github in addition to pushing tags, just because it binds pythran a bit more to that platform, and it requires extra steps on my side to do a release.

**Comment by serge-sans-paille** [comment]
oh, and btw, whenever I do a release I publish an email with extra info on `pythran@freelists.org`, see https://www.freelists.org/list/pythran

**Comment by kloczek** [comment]
Thank you 👍
