### ISSUE TITLE
pythran vs cython vs numba vs nukia ...

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#458]
hi,

I've read several conference papers relating to `pythran` but still need to ask few questions. It's great if `pythran` developers could discuss.

Before knowing `pythran`, I only really paid attention to `cython` and `numba`. I chose `cython` over `numba` because cython is very portable. I just need to include c++ cythonized files to [my package](https://github.com/pytraj/pytraj) without bothering about installing LLVM  and other dependent stuff.  And cython works really well with C++ class.

Later I know `pythran` when watching your talk (youtube). From reading your papers, it seems that `pythran` dev really want to focus on `openmp` (and simd too?) with more control on how openmp work (similiar to c/c++); which is very great bonus.

so,

* How `pythran` can survive among many other compilers? 
* how `pythran` can support calling c++ class like `cython` (great thing in cython)
* it's likely that `pythran` heavily depend on `boost` and `nt2`, which require `conda` to manage the installation. How `pythran` can "beat" `numba`? :D 
* is there any intention to speeding up compiling code? Linking cythonzied code to c++ lib is quite slow but compiling `.so` file in `pythran` is even slower.

(still have other questions but don't remember)

Hai

**Comment by pbrunet** [comment]
Hi hainm,

I can't answer to all of your questions but serge will do it for me.

1) How `pythran` can survive among many other compilers?
I think we have 3 mains asset for this.
- good speed up which is what is required most of the time when someone is looking for a python compiler
- backward compatibility. So that users can test Pythran almost for free (it is not free, they have to install pythran)
- Many features. We support an increasing and important part of the Python language. Many others compiler are really specifics and can't compile many code we can find in stackoverflow.

I really think we should focus on it.

2) how `pythran` can support calling `c++` class like cython (great thing in cython)
I didn't know about this feature but I am not sure we want to have it in Pythran as it break backward compatibility. Something more interesting could be support for classes combined with ctypes support. Do you have any arguments against this?

4) Is there any intention to speeding up compiling code? Linking cythonzied code to c++ lib is quite slow but compiling .so file in pythran is even slower.

Of course !!! I have some ideas for this but not enough time for now to do everything :-(

BTW, I looked at your package for my own curiosity and I think we could be great thing with it and even more in a near future as we will focus on this kind of code with the OpenDreamKit project.

**Comment by hainm** [comment]
> backward compatibility. So that users can test Pythran almost for free (it is not free, they have to install pythran)

Can you elaborate this? I don't quite understand about 'free' part.

>> 2) how pythran can support calling c++ class like cython (great thing in cython)

> I didn't know about this feature but I am not sure we want to have it in Pythran as it break backward compatibility. Something more interesting could be support for classes combined with ctypes support. Do you have any arguments against this?

I think support calling c++ is great deal since there are so many c++ lib out there. python compilers can make faster but still within c++ speed. :P Among all compilers, I think `Cython` does really great job on this. My `pytraj` packge is Python-binding to existing c++ lib so it's very natural to use cython ins this project.

>> 4) Is there any intention to speeding up compiling code? Linking cythonzied code to c++ lib is quite slow but compiling .so file in pythran is even slower.

> Of course !!! I have some ideas for this but not enough time for now to do everything :-(

Agree. This is only minor point.

**Comment by pbrunet** [comment]
When I say that users can try Pythran for free I mean they doesn't need to really change their codes. It is a pure Python input and they doesn't need an extra effort to remove Pythran support if they don't like it.  (Not like Cython for example)

About c++ class I though it was possible to do it with ctypes but as mentionned in many stasckoverflow issue, it is not possible because of mangling names which are not standard.
I don't really like the idea to introduce it in Pythran because it will break the "backward compatibility" but I have to admit that it is certainly a great feature for users like you.
I also wonder how can you handles typing between your c++ code and the Cython one?
@serge-sans-paille what do you think about it?

**Comment by hainm** [comment]
> When I say that users can try Pythran for free I mean they doesn't need to really change their codes. It is a pure Python input and they doesn't need an extra effort to remove Pythran support if they don't like it. (Not like Cython for example)

I agree. +1 (vs `Cython`, `numba`).

per 'ctypes', I think it only support C but not C++ class (or may be too complicated?) ?

> I also wonder how can you handles typing between your c++ code and the Cython one?

It's great that `cython` allow to mix python and c++ everywhere. Whenever you need C++ vector (just for example), just declare it and use it. It's very straight forward. 

For example, I just mixed C++ vector iterator + cython memoryview + python method in single function here. Very flexible. 

https://github.com/pytraj/pytraj/blob/master/pytraj/Trajectory.pyx#L778

**Comment by hainm** [comment]
oh, I've been thinking about useful case for pythran, given that it has many dependencies. But now we have conda, developers can use conda + pythranize to build their package and ship to user. The installation seems much easier with this case.

**Comment by hainm** [comment]
FYI: there is a PR in cython that use `pythran` for numpy:

https://github.com/cython/cython/pull/1607
