### ISSUE TITLE
type destrucring is no longer compatible with OpenMP

### ISSUE THREAD

**Issue by serge-sans-paille** [serge-sans-paille/pythran#596]
a ``#omp critical`` on a type destructuring assignement no longer works.

**Comment by serge-sans-paille** [comment]
Should be fixed by #597

**Comment by pbrunet** [comment]
Sorry but I don't understand how this is fix. For now, the critical section is set only on the first node.

eg:

```python
# critical is here
_tuple = foo()
z = _tuple[0]
y = _tuple[1]
```

But  you may still have parallelism issue with:

```python
def main():
    a = [1, 2]
    #omp parallel threads(2)
    bar(a)

def bar(a)
    #omp critical
    a[0], a[1] = foo(omp_get_thread_num(), a)
    print a
```

you have thread safety issue. What will be the result for thread 0?
the result of foo for thread 0? Or a mix with thread 1's result as a may be change while it is use in the foo function?

I guess, we will need to reintroduce the "if" statement or we can modernize generated code and use std::tie instead of performing unpacking ourselves.

**Comment by serge-sans-paille** [comment]
On Sun, Aug 14, 2016 at 12:15:58PM -0700, pbrunet wrote:
> Sorry but I don't understand how this is fix. For now, the critical section is set only on the first node.
> 
> eg:
> 
> ```python
> # critical is here
> _tuple = foo()
> z = _tuple[0]
> y = _tuple[1]
> ```
> 
> But  you may still have parallelism issue with:
> 
> ```python
> def main():
>     a = [1, 2]
>     #omp parallel threads(2)
>     bar(a)
> 
> def bar(a)
>     #omp critical
>     a[0], a[1] = foo(omp_get_thread_num(), a)
>     print a
> ```
> 
> you have thread safety issue. What will be the result for thread 0?
> the result of foo for thread 0? Or a mix with thread 1's result as a may be change while it is use in the foo function?
> 
> I guess, we will need to reintroduce the "if" statement or we can modernize generated code and use std::tie instead of performing unpacking ourselves.

You're 100% rright. i'll favor the if though, as many analysis don't
support assignment if type destructuring is not done
