### ISSUE TITLE
Compilation switch

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#710]
Provide a wait to enable/disable code when compiled with pythran or executed with python

**Comment by serge-sans-paille** [comment]
So the idea is to allow this kind of code

```
def foo(x):
    if hasattr(__module__, 'pythran'):
        # pythran implem
    else:
        # python implem
```

This would behave somehow like a preprocessing step, ``#ifdef PYTHRAN``. Unfortunaltely, this is very ad-hoc (what about ``if not not hasattr(__module__, 'pythran'):`` ? there are multiple ways of expressiing the condition, store the expression in a global etc).

I don't want to make it an idiom, nor do I want to implement a generic pre procesisng step. Note that because any Python code could go in the else section... So it's not a valid Pythran inout and the preprocessing step should be ware of that.

There's still the currently working solution to put the pythonic version of foo in the calling module and test wether the imported pythran module has the '__pythran__' attribute, isn't that enough?

**Comment by diorcety** [comment]
I'm understand but i don't see the limitation. It is only a kind a preprocessor, by replacing `hasattr(__module__, 'pythran') ` by `True`, before process it like normal python code.
`if not not hasattr(__module__, 'pythran'):` will give `if not not True:`

**Comment by diorcety** [comment]
I could almost do it by a grep before processing the file.

**Comment by serge-sans-paille** [comment]
I reognize there are a lot of simple hacky way to achieve this goal, the problem (to me) is that it would introduce a preprocessing step in pythran, which I don't like that much until there's strong evidence it's needed.
